Aptly upload scripts: Safer + Better version extraction
* Fixed all warnings shown by ShellCheck.net

* Improved file listing with 'ls -v'.
Given these files:
kurento-media-server_6.12.0.deb
kurento-media-server_6.8.0.deb

The latest one is "6.12.0", but normal string sorting rules would
wrongly choose "6.8.0". Solution is to use the "Version number aware
sorting" that is available in 'ls'.

* Improved version number extraction in grep regex.
Given this version string:
6.12.0.xenial.20180927190733.be576e8

The used regex will not match the "12" because there is more than 1
digit. The new regex expects '1 or more' digits on each part.

* Improved file glob for package files.

With '*.deb' we would ignore default debug debian packages, that are
named '*.ddeb'. Using the new glob includes these also. The new default
naming for debian debug packages will be used soon in Kurento repos.

diff --git a/development/aptly_management b/development/aptly_management
--- a/development/aptly_management
+++ b/development/aptly_management
@@ -1,19 +1,24 @@
 #!/bin/bash -x
-set -eu -o pipefail 
+
+# Strict error checking
+set -o errexit -o errtrace -o pipefail -o nounset
 
 echo "##################### EXECUTE: aptly_management #####################"
 
-KMS_DEB_PKG=$(ls -1 kurento-media-server* | head -n 1)
-[ ! -z "$KMS_DEB_PKG" ] || exit 1 
+# shellcheck disable=SC2012
+KMS_DEB_PKG="$(ls -v -1 kurento-media-server_*.deb | tail -n 1)"
+[ -z "$KMS_DEB_PKG" ] && { echo "Cannot find KMS package"; exit 1; }
 
-RELEASE=$(dpkg -f "$KMS_DEB_PKG" Version | grep -Po '^\d.\d.\d')
-[ ! -z "$RELEASE" ] || exit 1
+KMS_VERSION="$(
+    dpkg --field "$KMS_DEB_PKG" Version \
+        | grep --perl-regexp --only-matching '^(\d+\.\d+\.\d+)'
+)"
+[ -z "$KMS_VERSION" ] && { echo "Cannot parse KMS Version field"; exit 1; }
 
 # Get external packages
-aws s3 sync s3://ubuntu.openvidu.io/externals/${DISTRIBUTION}/ .
+aws s3 sync "s3://ubuntu.openvidu.io/externals/${DISTRIBUTION}/" .
 
-aptly repo create -distribution=$DISTRIBUTION -component=kms6 kurento-$DISTRIBUTION-$RELEASE
-aptly repo add kurento-$DISTRIBUTION-$RELEASE *.deb 
-aptly snapshot create snap-kurento-$DISTRIBUTION-$RELEASE from repo kurento-$DISTRIBUTION-$RELEASE
-aptly -gpg-key=$GPGKEY publish snapshot snap-kurento-$DISTRIBUTION-$RELEASE s3:ubuntu:$RELEASE
-
+aptly repo create -distribution="${DISTRIBUTION}" -component=kms6 "kurento-${DISTRIBUTION}-${KMS_VERSION}"
+aptly repo add "kurento-${DISTRIBUTION}-${KMS_VERSION}" ./*.*deb
+aptly snapshot create "snap-kurento-${DISTRIBUTION}-${KMS_VERSION}" from repo "kurento-${DISTRIBUTION}-${KMS_VERSION}"
+aptly -gpg-key="${GPGKEY}" publish snapshot "snap-kurento-${DISTRIBUTION}-${KMS_VERSION}" "s3:ubuntu:${KMS_VERSION}"
