Dev scripts: Add log function

diff --git a/development/kurento-git-clone-externals b/development/kurento-git-clone-externals
--- a/development/kurento-git-clone-externals
+++ b/development/kurento-git-clone-externals
@@ -10,46 +10,51 @@ IFS=$'\n\t'          # Apply word splitting only on newlines and tabs
 # 2018-02-13
 # - Print the list of repos that will get cloned.
 # - Don't hide stderr from `git clone`.
+# 2018-03-23
+# - Add log function.
+
+# Set up logging function
+BASENAME="$(basename "$0")"  # Complete file name
+log() { echo "[$BASENAME] $*"; }
 
 # Settings
 BASE_URL="https://github.com/Kurento"
 
 REPOS=(
-  gstreamer
-  libsrtp
-  openh264
-  usrsctp
-  jsoncpp
-  gst-plugins-base
-  gst-plugins-good
-  gst-plugins-ugly
-  gst-plugins-bad
-  gst-libav
-  openwebrtc-gst-plugins
-  libnice
+    gstreamer
+    libsrtp
+    openh264
+    usrsctp
+    jsoncpp
+    gst-plugins-base
+    gst-plugins-good
+    gst-plugins-ugly
+    gst-plugins-bad
+    gst-libav
+    openwebrtc-gst-plugins
+    libnice
 )
 
-echo "==== Clone Git repositories ===="
-echo "This script will clone all Kurento External repos:"
+log "==== Clone Git repositories ===="
+log "This script will clone all Kurento External repos:"
 printf '%s\n' "${REPOS[@]}"
 read -p "Are you sure? Type 'yes': " -r SURE
-[ "$SURE" != "yes" ] && [ "$SURE" != "YES" ] && { echo "Aborting"; exit 1; }
+[ "$SURE" != "yes" ] && [ "$SURE" != "YES" ] && { log "Aborting"; exit 1; }
 
-echo "Working..."
+log "Working..."
 
 for REPO in "${REPOS[@]}"; do
-  REPO_URL="${BASE_URL}/${REPO}"
-  if [ -d "$REPO" ]; then
-    echo "Skip already existing: $REPO"
-  else
-    echo "Clone repository: $REPO"
-    git clone "$REPO_URL" >/dev/null
-  fi
+    REPO_URL="${BASE_URL}/${REPO}"
+    if [ -d "$REPO" ]; then
+        log "Skip already existing: $REPO"
+    else
+        log "Clone repository: $REPO"
+        git clone "$REPO_URL" >/dev/null
+    fi
 done
 
-echo ""
-echo "Git repositories cloned at ${PWD}/"
+log "Git repositories cloned at ${PWD}/"
 
 # ------------
 
-echo "[$0] Done."
+log "Done."
diff --git a/development/kurento-git-clone-kms b/development/kurento-git-clone-kms
--- a/development/kurento-git-clone-kms
+++ b/development/kurento-git-clone-kms
@@ -12,70 +12,75 @@ IFS=$'\n\t'          # Apply word splitting only on newlines and tabs
 # 2018-02-13
 # - Print the list of repos that will get cloned.
 # - Don't hide stderr from `git clone`.
+# 2018-03-23
+# - Add log function.
+
+# Set up logging function
+BASENAME="$(basename "$0")"  # Complete file name
+log() { echo "[$BASENAME] $*"; }
 
 # Settings
 BASE_URL="https://github.com/Kurento"
 
 REPOS=(
-  # KMS main components
-  kms-omni-build
-  kurento-module-creator
-  kms-cmake-utils
-  kms-jsonrpc
-  kms-core
-  kms-elements
-  kms-filters
-  kurento-media-server
+    # KMS main components
+    kms-omni-build
+    kurento-module-creator
+    kms-cmake-utils
+    kms-jsonrpc
+    kms-core
+    kms-elements
+    kms-filters
+    kurento-media-server
 
-  # KMS extra modules
-  kms-chroma
-  kms-crowddetector
-  kms-datachannelexample
-  kms-platedetector
-  kms-pointerdetector
+    # KMS extra modules
+    kms-chroma
+    kms-crowddetector
+    kms-datachannelexample
+    kms-platedetector
+    kms-pointerdetector
 
-  # Additional sample modules
-  kms-markerdetector
-  kms-opencv-plugin-sample
-  kms-plugin-sample
+    # Additional sample modules
+    kms-markerdetector
+    kms-opencv-plugin-sample
+    kms-plugin-sample
 
-  # Tools and documentation
-  adm-scripts
-  bugtracker
-  doc-kurento
+    # Tools and documentation
+    adm-scripts
+    bugtracker
+    doc-kurento
 
-  # Client Applications related repos
-  kurento-maven-plugin
-  kurento-qa-pom
-  kurento-java
-  kurento-tutorial-java
-  kurento-tutorial-test
+    # Client Applications related repos
+    kurento-maven-plugin
+    kurento-qa-pom
+    kurento-java
+    kurento-tutorial-java
+    kurento-tutorial-test
 
-  # Miscellaneous experiments
-  experiments
+    # Miscellaneous experiments
+    experiments
 )
 
-echo "==== Clone Git repositories ===="
-echo "This script will clone all Kurento repos:"
+log "==== Clone Git repositories ===="
+log "This script will clone all Kurento repos:"
 printf '%s\n' "${REPOS[@]}"
 read -p "Are you sure? Type 'yes': " -r SURE
-[ "$SURE" != "yes" ] && [ "$SURE" != "YES" ] && { echo "Aborting"; exit 1; }
+[ "$SURE" != "yes" ] && [ "$SURE" != "YES" ] && { log "Aborting"; exit 1; }
 
-echo "Working..."
+log "Working..."
 
 for REPO in "${REPOS[@]}"; do
-  REPO_URL="${BASE_URL}/${REPO}"
-  if [ -d "$REPO" ]; then
-    echo "Skip already existing: $REPO"
-  else
-    echo "Clone repository: $REPO"
-    git clone "$REPO_URL" >/dev/null
-  fi
+    REPO_URL="${BASE_URL}/${REPO}"
+    if [ -d "$REPO" ]; then
+        log "Skip already existing: $REPO"
+    else
+        log "Clone repository: $REPO"
+        git clone "$REPO_URL" >/dev/null
+    fi
 done
 
-echo ""
-echo "Git repositories cloned at ${PWD}/"
+log "Git repositories cloned at ${PWD}/"
 
 # ------------
 
-echo "[$0] Done."
+log "Done."
diff --git a/development/kurento-repo-xenial-release b/development/kurento-repo-xenial-release
--- a/development/kurento-repo-xenial-release
+++ b/development/kurento-repo-xenial-release
@@ -7,9 +7,15 @@ IFS=$'\n\t'          # Apply word splitting only on newlines and tabs
 # Changes:
 # 2017-10-03 Juan Navarro <juan.navarro@gmx.es>
 # - Initial version.
+# 2018-03-23
+# - Add log function.
+
+# Set up logging function
+BASENAME="$(basename "$0")"  # Complete file name
+log() { echo "[$BASENAME] $*"; }
 
 # Check root permissions
-[ "$(id -u)" -eq 0 ] || { echo "Please run as root"; exit 1; }
+[ "$(id -u)" -eq 0 ] || { log "Please run as root"; exit 1; }
 
 # Settings
 FILE="/etc/apt/sources.list.d/kurento.list"
@@ -21,19 +27,19 @@ deb http://ubuntu.kurento.org ${REPO} kms6
 EOF
 
 gpg --list-public-keys --no-default-keyring --keyring /etc/apt/trusted.gpg \
-  --with-colons | grep -q "Kurento" && RC=$? || RC=$?
+    --with-colons | grep -q "Kurento" && RC=$? || RC=$?
 
 if [ "$RC" -eq 1 ]; then
-  wget http://ubuntu.kurento.org/kurento.gpg.key -O - | apt-key add -
+    wget http://ubuntu.kurento.org/kurento.gpg.key -O - | apt-key add -
 elif [ "$RC" -ne 0 ]; then
-  echo "ERROR ($RC)"
-  exit "$RC"
+    log "ERROR ($RC)"
+    exit "$RC"
 fi
 
 apt-get update
 
-echo "Repository '$REPO' configured at $FILE"
+log "Repository '$REPO' configured at $FILE"
 
 # ------------
 
-echo "[$0] Done."
+log "Done."
