development/*: Standalone (no error when bash.conf is missing)

diff --git a/development/kurento-install-development b/development/kurento-install-development
--- a/development/kurento-install-development
+++ b/development/kurento-install-development
@@ -17,7 +17,10 @@
 
 BASEPATH="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"  # Absolute canonical path
 # shellcheck source=bash.conf.sh
-source "$BASEPATH/../bash.conf.sh" || exit 1
+source "$BASEPATH/../bash.conf.sh" || {
+    # Bash options for strict error checking
+    set -o errexit -o errtrace -o pipefail -o nounset
+}
 
 
 
@@ -25,7 +28,7 @@ source "$BASEPATH/../bash.conf.sh" || exit 1
 # -----------------
 
 [[ "$(id -u)" -eq 0 ]] || {
-    log "ERROR: Please run as root user (or with 'sudo')"
+    echo "ERROR: Please run as root user (or with 'sudo')"
     exit 1
 }
 
@@ -62,10 +65,10 @@ DIRS=(
     kurento-media-server
 )
 for DIR in "${DIRS[@]}"; do
-    log "Install Build-Depends for '${DIR}'"
+    echo "+ Install Build-Depends for '${DIR}'"
     mk-build-deps --install --remove \
         --tool='apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes' \
         "${DIR}/debian/control"
 done
 
-log "All packages installed successfully"
+echo "All packages installed successfully"
diff --git a/development/kurento-uninstall-all b/development/kurento-uninstall-all
--- a/development/kurento-uninstall-all
+++ b/development/kurento-uninstall-all
@@ -13,7 +13,10 @@
 
 BASEPATH="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"  # Absolute canonical path
 # shellcheck source=bash.conf.sh
-source "$BASEPATH/../bash.conf.sh" || exit 1
+source "$BASEPATH/../bash.conf.sh" || {
+    # Bash options for strict error checking
+    set -o errexit -o errtrace -o pipefail -o nounset
+}
 
 
 
@@ -21,7 +24,7 @@ source "$BASEPATH/../bash.conf.sh" || exit 1
 # -----------------
 
 [[ "$(id -u)" -eq 0 ]] || {
-    log "ERROR: Please run as root user (or with 'sudo')"
+    echo "ERROR: Please run as root user (or with 'sudo')"
     exit 1
 }
 
@@ -66,7 +69,7 @@ PACKAGES=(
 # apt-get won't allow unexisting names, so we cannot do it the fancy way
 # and uninstall everything on a single command. Blame's on you, apt-get.
 for PACKAGE in "${PACKAGES[@]}"; do
-    apt-get purge --auto-remove --yes "$PACKAGE" || { log "Skip unexisting"; }
+    apt-get purge --auto-remove --yes "$PACKAGE" || { echo "Skip unexisting"; }
 done
 
-log "All packages uninstalled successfully"
+echo "All packages uninstalled successfully"
