Developer scripts: General update

diff --git a/development/kurento-install-debugging b/development/kurento-install-debugging
--- a/development/kurento-install-debugging
+++ b/development/kurento-install-debugging
@@ -1,72 +1,102 @@
 #!/usr/bin/env bash
-set -eu -o pipefail  # Abort on errors, disallow undefined variables
-IFS=$'\n\t'          # Apply word splitting only on newlines and tabs
 
 # Install debugging symbols for Kurento Media Server.
-#
-# Changes:
-# 2018-02-12 Juan Navarro <juan.navarro@gmx.es>
-# - Initial version (merged from other install scripts).
-# - Add package: libsrtp1-dbg.
-# 2018-03-16
-# - Add command line argument parsing with 'getopts'.
-# - Add argument '-n' to skip running `apt-get update`.
-# 2018-03-23
-# - Add log function.
 
-# Set up logging function
-BASENAME="$(basename "$0")"  # Complete file name
-log() { echo "[$BASENAME] $*"; }
 
-# Check root permissions
-[ "$(id -u)" -eq 0 ] || { log "Please run as root"; exit 1; }
+
+# Shell setup
+# -----------
+
+BASEPATH="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"  # Absolute canonical path
+# shellcheck source=bash.conf.sh
+source "$BASEPATH/../bash.conf.sh" || exit 1
+
+
+
+# Check permissions
+# -----------------
+
+[[ "$(id -u)" -eq 0 ]] || {
+    log "ERROR: Please run as root user (or with 'sudo')"
+    exit 1
+}
+
+
+
+# Ask for confirmation
+# --------------------
+
+echo "==== Install Kurento debug symbols ===="
+echo "This will add the Ubuntu 'dbgsym' repository sources"
+echo ""
+read -p "Are you sure? Type 'yes': " -r SURE
+if [[ "$SURE" != "yes" && "$SURE" != "YES" ]]; then
+    echo "Exit ..."
+    exit 0
+fi
+
+
+
+# Add Ubuntu 'dbgsym' repository sources
+# --------------------------------------
+
+if [[ -f /etc/upstream-release/lsb-release ]]; then
+    source /etc/upstream-release/lsb-release
+else
+    source /etc/lsb-release
+fi
+
+tee /etc/apt/sources.list.d/ddebs.list >/dev/null <<EOF
+# Ubuntu '-dbgsym.ddeb' (debug symbols) packages
+deb http://ddebs.ubuntu.com ${DISTRIB_CODENAME} main restricted universe multiverse
+deb http://ddebs.ubuntu.com ${DISTRIB_CODENAME}-updates main restricted universe multiverse
+deb http://ddebs.ubuntu.com ${DISTRIB_CODENAME}-proposed main restricted universe multiverse
+EOF
+
+apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F2EDC64DC5AEE1F6B9C621F0C8CAB6595FDFF622
+
+apt-get update
+
+
+
+# Install debug symbols
+# ---------------------
 
 PACKAGES=(
-    # Third-party libraries
-    libglib2.0-0-dbg
-    libssl1.0.0-dbg
+    # System libraries
+    libglib2.0-0-dbgsym
+    libsrtp0-dbgsym
+    libssl1.0.0-dbgsym
 
-    # Kurento external libraries
+    # Fork packages
+    kmsjsoncpp-dbg
+    libusrsctp-dbgsym
+    libgstreamer1.5-0-dbg
     gstreamer1.5-plugins-base-dbg
     gstreamer1.5-plugins-good-dbg
-    gstreamer1.5-plugins-ugly-dbg
     gstreamer1.5-plugins-bad-dbg
+    gstreamer1.5-plugins-ugly-dbg
     gstreamer1.5-libav-dbg
-    libgstreamer1.5-0-dbg
-    libnice-dbg
-    libsrtp1-dbg
     openwebrtc-gst-plugins-dbg
-    kmsjsoncpp-dbg
+    libnice10-dbgsym
+    gstreamer1.5-nice-dbgsym
 
-    # KMS main components
-    kms-jsonrpc-1.0-dbg
-    kms-core-6.0-dbg
-    kms-elements-6.0-dbg
-    kms-filters-6.0-dbg
-    kurento-media-server-6.0-dbg
+    # Main packages
+    kms-jsonrpc-dbg
+    kms-core-dbg
+    kms-elements-dbg
+    kms-filters-dbg
+    kurento-media-server-dbg
 
-    # KMS extra modules
-    kms-chroma-6.0-dbg
-    kms-crowddetector-6.0-dbg
-    kms-platedetector-6.0-dbg
-    kms-pointerdetector-6.0-dbg
+    # Extra packages
+    #kms-chroma-dbg
+    #kms-crowddetector-dbg
+    #kms-platedetector-dbg
+    #kms-pointerdetector-dbg
 )
 
-# Parse command line arguments
-update=1
-while getopts 'n' flag; do
-    case "${flag}" in
-        n) update=0 ;;
-        *) ;;
-    esac
-done
-
-(( $update )) && apt-get update
-
-apt-get install --yes "${PACKAGES[@]}"
+apt-get update \
+  && apt-get install --no-install-recommends --yes \
+     "${PACKAGES[@]}"
 
 log "All packages installed successfully"
-
-# ------------
-
-log "Done."
diff --git a/development/kurento-install-development b/development/kurento-install-development
--- a/development/kurento-install-development
+++ b/development/kurento-install-development
@@ -1,6 +1,4 @@
 #!/usr/bin/env bash
-set -eu -o pipefail  # Abort on errors, disallow undefined variables
-IFS=$'\n\t'          # Apply word splitting only on newlines and tabs
 
 # Install packages needed to build Kurento Media Server.
 #
@@ -11,114 +9,63 @@ IFS=$'\n\t'          # Apply word splitting only on newlines and tabs
 # Notes:
 # - gstreamer1.5-x is needed for the "timeoverlay" GStreamer plugin,
 #   used by some tests in kms-elements.
-#
-# Changes:
-# 2017-10-03 Juan Navarro <juan.navarro@gmx.es>
-# - Initial version.
-# 2018-02-02
-# - Use a Bash Array to define all packages; run a single `apt-get` command.
-# 2018-02-07
-# - Add package: gstreamer1.5-tools.
-# 2018-02-12
-# - Move debugging packages to their own install script.
-# 2018-02-25
-# - Remove 'clang' and sort dev tools by name.
-# 2018-03-16
-# - Add command line argument parsing with 'getopts'.
-# - Add argument '-n' to skip running `apt-get update`.
-# 2018-03-23
-# - Add log function.
-# - FIXME for Trusty: openwebrtc-gst-plugins=0.10.0.20160909214034.trusty
 
-# Set up logging function
-BASENAME="$(basename "$0")"  # Complete file name
-log() { echo "[$BASENAME] $*"; }
 
-# Check root permissions
-[ "$(id -u)" -eq 0 ] || { log "Please run as root"; exit 1; }
 
-PACKAGES=(
-    # Development tools
-    build-essential
-    cmake
-    debhelper
-    default-jdk
-    gdb
-    git openssh-client
-    maven
-    pkg-config
-    wget
+# Shell setup
+# -----------
 
-    # 'maven-debian-helper' installs an old Maven version in Ubuntu 14.04 (Trusty),
-    # so this ensures that the effective version is the one from 'maven'.
-    maven-debian-helper-
+BASEPATH="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"  # Absolute canonical path
+# shellcheck source=bash.conf.sh
+source "$BASEPATH/../bash.conf.sh" || exit 1
 
-    # System development libraries
-    libboost-dev
-    libboost-filesystem-dev
-    libboost-log-dev
-    libboost-program-options-dev
-    libboost-regex-dev
-    libboost-system-dev
-    libboost-test-dev
-    libboost-thread-dev
-    libevent-dev
-    libglib2.0-dev
-    libglibmm-2.4-dev
-    libopencv-dev
-    libsigc++-2.0-dev
-    libsoup2.4-dev
-    libssl-dev
-    libvpx-dev
-    libxml2-utils
-    uuid-dev
 
-    # Kurento external libraries
-    gstreamer1.5-plugins-base
-    gstreamer1.5-plugins-good
-    gstreamer1.5-plugins-ugly
-    gstreamer1.5-plugins-bad
-    gstreamer1.5-libav
-    gstreamer1.5-nice
-    gstreamer1.5-tools
-    gstreamer1.5-x
-    libgstreamer1.5-dev
-    libgstreamer-plugins-base1.5-dev
-    libnice-dev
-    openh264-gst-plugins-bad-1.5
-    #openwebrtc-gst-plugins-dev # FIXME - Workaround for Ubuntu 14.04 (Trusty)
-    kmsjsoncpp-dev
-    ffmpeg
-)
 
-# Parse command line arguments
-update=1
-while getopts 'n' flag; do
-    case "${flag}" in
-        n) update=0 ;;
-        *) ;;
-    esac
-done
+# Check permissions
+# -----------------
 
-(( $update )) && apt-get update
+[[ "$(id -u)" -eq 0 ]] || {
+    log "ERROR: Please run as root user (or with 'sudo')"
+    exit 1
+}
 
-apt-get install --yes "${PACKAGES[@]}"
 
-# FIXME - Workaround for Ubuntu 14.04 (Trusty)
-if [ "$(lsb_release -sc)" = "trusty" ]; then
-    apt-get install --yes \
-        openwebrtc-gst-plugins=0.10.0.20160909214034.trusty \
-        openwebrtc-gst-plugins-dev=0.10.0.20160909214034.trusty \
-    || apt-get install --yes \
-        openwebrtc-gst-plugins=0.10.0.1.trusty~20180213160509.1.33ccf19 \
-        openwebrtc-gst-plugins-dev=0.10.0.1.trusty~20180213160509.1.33ccf19
-else
-    apt-get install --yes \
-        openwebrtc-gst-plugins-dev
+
+# Ask for confirmation
+# --------------------
+
+echo "==== Install Kurento build dependencies ===="
+echo "This script should be run from 'kms-omni-build'"
+echo ""
+read -p "Are you sure? Type 'yes': " -r SURE
+if [[ "$SURE" != "yes" && "$SURE" != "YES" ]]; then
+    echo "Exit ..."
+    exit 0
 fi
 
+
+
+# Install Build-Depends
+# ---------------------
+
+apt-get update \
+  && apt-get install --no-install-recommends --yes \
+     git devscripts equivs
+
+DIRS=(
+    kurento-module-creator
+    kms-cmake-utils
+    kms-jsonrpc
+    kms-core
+    kms-elements
+    kms-filters
+    kurento-media-server
+)
+for DIR in "${DIRS[@]}"; do
+    log "Install Build-Depends for '${DIR}'"
+    mk-build-deps --install --remove \
+        --tool='apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes' \
+        "${DIR}/debian/control"
+done
+
 log "All packages installed successfully"
-
-# ------------
-
-log "Done."
diff --git a/development/kurento-uninstall-all b/development/kurento-uninstall-all
--- a/development/kurento-uninstall-all
+++ b/development/kurento-uninstall-all
@@ -1,45 +1,54 @@
 #!/usr/bin/env bash
-set -eu -o pipefail  # Abort on errors, disallow undefined variables
-IFS=$'\n\t'          # Apply word splitting only on newlines and tabs
 
 # Uninstall every packge related to KMS and its development.
 #
 # Sources:
 # - Installation scripts.
 # - Installing KMS and running `aptitude search '~mkurento'`.
-#
-# Changes:
-# 2017-10-03 Juan Navarro <juan.navarro@gmx.es>
-# - Initial version.
-# 2018-02-02
-# - Use a Bash Array to define all packages.
-# 2018-03-23
-# - Add log function.
 
-# Set up logging function
-BASENAME="$(basename "$0")"  # Complete file name
-log() { echo "[$BASENAME] $*"; }
 
-# Check root permissions
-[ "$(id -u)" -eq 0 ] || { log "Please run as root"; exit 1; }
+
+# Shell setup
+# -----------
+
+BASEPATH="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"  # Absolute canonical path
+# shellcheck source=bash.conf.sh
+source "$BASEPATH/../bash.conf.sh" || exit 1
+
+
+
+# Check permissions
+# -----------------
+
+[[ "$(id -u)" -eq 0 ]] || {
+    log "ERROR: Please run as root user (or with 'sudo')"
+    exit 1
+}
+
+
+
+# Uninstall everything
+# --------------------
 
 PACKAGES=(
-    # KMS main components + extra modules
+    # Main+Extra packages
     '^(kms|kurento).*'
 
-    # Kurento external libraries
-    ffmpeg
-    '^gir1.2-gst.*1.5'
-    gir1.2-nice-0.1
-    '^(lib)?gstreamer.*1.5.*'
-    '^lib(nice|s3-2|srtp|usrsctp).*'
-    '^srtp-.*'
+    # Fork packages
+    '^kmsjsoncpp.*'
+    '^libsrtp1.*'
     '^openh264(-gst-plugins-bad-1.5)?'
+    '^libusrsctp.*'
+    '^(lib)?gstreamer.*1.5.*'
+    '^gir1.2-gst.*1.5'
     '^openwebrtc-gst-plugins.*'
+    gir1.2-nice-0.1
+    '^lib(nice|s3-2).*'
 
-    # System development libraries
+    # System libraries
     '^libboost-?(filesystem|log|program-options|regex|system|test|thread)?-dev'
     '^lib(glib2.0|glibmm-2.4|opencv|sigc++-2.0|soup2.4|ssl|tesseract|vpx)-dev'
+    '^srtp-.*'
     uuid-dev
 
     # Packages installed by kurento-module-creator
@@ -54,14 +63,10 @@ PACKAGES=(
 )
 
 # Run a loop over all names and uninstall them.
-# apt-get is *stupid*, and won't allow unexisting names, so we cannot do it
-# the fancy way and run a single `apt-get` command.
+# apt-get won't allow unexisting names, so we cannot do it the fancy way
+# and uninstall everything on a single command. Blame's on you, apt-get.
 for PACKAGE in "${PACKAGES[@]}"; do
     apt-get purge --auto-remove --yes "$PACKAGE" || { log "Skip unexisting"; }
 done
 
 log "All packages uninstalled successfully"
-
-# ------------
-
-log "Done."
