Update script to allow developer execution not from /usr/bin folder
Change-Id: I5316a5e38416a2fae5a1cec3283451b47558ad90

diff --git a/scripts/kurento-module-creator b/scripts/kurento-module-creator
--- a/scripts/kurento-module-creator
+++ b/scripts/kurento-module-creator
@@ -2,6 +2,21 @@
 
 JAVA_CMD="/usr/bin/java"
 JAVA_OPTS=""
-JAVA_JAR="/usr/bin/kurento-module-creator-jar-with-dependencies.jar"
+
+MY_PATH=`dirname "$0"`
+MY_PATH=`( cd "$MY_PATH" && pwd )`
+if [ -z "$MY_PATH" ] ; then
+  # error; for some reason, the path is not accessible
+  # to the script (e.g. permissions re-evaled after suid)
+  exit 1  # fail
+fi
+
+if [ "${MY_PATH}" = "/usr/bin" ]
+then
+  JAVA_JAR="/usr/bin/kurento-module-creator-jar-with-dependencies.jar"
+else
+  echo Not system kurento-module-creator, running from $MY_PATH
+  JAVA_JAR=${MY_PATH}/../target/kurento-module-creator-jar-with-dependencies.jar
+fi
 
 $JAVA_CMD $JAVA_OPTS -jar "$JAVA_JAR" "$@"
