Prepare CI workflows for Java projects

diff --git a/.github/workflows/clients-java-parent.yaml b/.github/workflows/clients-java-parent.yaml
--- a/.github/workflows/clients-java-parent.yaml
+++ b/.github/workflows/clients-java-parent.yaml
@@ -1,16 +1,116 @@
 name: "Clients: Build All Java (Parent)"
 
 on:
-  # Manual trigger.
+  # Triggered manually.
   workflow_dispatch:
 
-  # Trigger from other job.
-  workflow_call:
-
 jobs:
-  build:
-    runs-on: "ubuntu-latest"
+  qa-pom:
+    runs-on: ["self-hosted", "dev"]
+    timeout-minutes: 30
     steps:
-      - name: "Say Hello"
+      # Action: https://github.com/actions/checkout
+      - name: "Checkout"
+        uses: "actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c" # v3.3.0
+
+      - name: "Configure the environment for ci-scripts/"
+        working-directory: "ci-scripts/"
         run: |
-          echo "Hello World!"
+          echo "$PWD" >>$GITHUB_PATH
+          echo "KURENTO_SCRIPTS_HOME=$PWD" >>$GITHUB_ENV
+          echo "JOB_TIMESTAMP=$(date --utc +%Y%m%d%H%M%S)" >>$GITHUB_ENV
+
+      - name: "Configure the environment for job script"
+        run: |
+          # APTLY_SSH_KEY_PATH="$RUNNER_TEMP/id_aptly"
+          # echo "APTLY_SSH_KEY_PATH=$APTLY_SSH_KEY_PATH" >>$GITHUB_ENV
+          # echo "${{ secrets.APTLY_SSH_PRIVATE_KEY }}" >"$APTLY_SSH_KEY_PATH"
+
+      - name: "Run job script"
+        env:
+          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
+          KURENTO_MAVEN_SONATYPE_USERNAME: "${{ secrets.KURENTO_MAVEN_SONATYPE_USERNAME }}"
+          KURENTO_MAVEN_SONATYPE_PASSWORD: "${{ secrets.KURENTO_MAVEN_SONATYPE_PASSWORD }}"
+          KURENTO_MAVEN_DOWNLOAD_USERNAME: "${{ secrets.KURENTO_MAVEN_DOWNLOAD_USERNAME }}"
+          KURENTO_MAVEN_DOWNLOAD_PASSWORD: "${{ secrets.KURENTO_MAVEN_DOWNLOAD_PASSWORD }}"
+          KURENTO_MAVEN_UPLOAD_USERNAME: "${{ secrets.KURENTO_MAVEN_UPLOAD_USERNAME }}"
+          KURENTO_MAVEN_UPLOAD_PASSWORD: "${{ secrets.KURENTO_MAVEN_UPLOAD_PASSWORD }}"
+          WORKSPACE_PATH: "${{ env.GITHUB_WORKSPACE }}"
+        # working-directory: "${{ inputs.directory }}"
+        run: |
+          # Compile, package, and deploy the current project.
+          "kurento_maven_deploy.sh"
+
+          # Only create a tag if the deployment process was successful.
+          # Allow errors because the tag might already exist (like if the release
+          # is being done again after solving some deployment issue).
+          "kurento_check_version.sh true || { echo 'WARNING: Command failed: kurento_check_version (tagging enabled)'; }"
+
+      # Action: https://github.com/actions/upload-artifact
+      - name: "Archive the artifacts"
+        uses: "actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce" # v3.1.2
+        with:
+          name: "artifacts"
+          path: "${{ inputs.directory }}/*.*deb"
+
+  # module-creator:
+  #   uses: "./.github/workflows/clients-java-build.reusable.yaml"
+
+  # maven-plugin:
+  #   needs: ["module-creator"]
+
+  # module-core:
+  #   needs: ["maven-plugin"]
+
+  # module-elements:
+  #   needs: ["module-core"]
+
+  # module-filters:
+  #   needs: ["module-elements"]
+
+  # client:
+  #   needs: ["qa-pom", "module-filters"]
+
+  # module-chroma:
+  #   needs: ["client"]
+
+  # module-crowddetector:
+  #   needs: ["client"]
+
+  # module-datachannelexample:
+  #   needs: ["client"]
+
+  # module-markerdetector:
+  #   needs: ["client"]
+
+  # module-platedetector:
+  #   needs: ["client"]
+
+  # module-pointerdetector:
+  #   needs: ["client"]
+
+  # kurento-utils-js:
+
+  # test-integration:
+  #   needs:
+  #     [
+  #       "kurento-utils-js",
+  #       "client",
+  #       "module-chroma",
+  #       "module-crowddetector",
+  #       "module-platedetector",
+  #     ]
+
+  # tutorials-java:
+  #   needs:
+  #     [
+  #       "client",
+  #       "module-chroma",
+  #       "module-crowddetector",
+  #       "module-datachannelexample",
+  #       "module-platedetector",
+  #       "module-pointerdetector",
+  #     ]
+
+  # tutorials-test:
+  #   needs: ["tutorials-java"]
